### ISSUE TITLE
Getting error accessing redirect.html

### ISSUE THREAD

**Issue by raisen** [MrSwitch/hello.js#480]
I'm getting Error 1014: CNAME Cross-User Banned from CloudFlare when I try to access:

https://adodson.com/hello.js/redirect.html

I'm trying to access this page from https://adodson.com/hello.js/#redirect-page

**Comment by MrSwitch** [comment]
Resolved by Cloudflare https://twitter.com/search?q=cloudflare%20error%201014&src=typd

**Comment by raisen** [comment]
It's still not working for me, but it looks like an issue on Cloudflare though as you mentioned. Thanks for the quick update.
